name: CI Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Start Redis
        uses: redis-labs/redis-action@v1.3
      
      - name: Run tests
        run: npm test
